### PR TITLE
[1.0.0] Update to ember-cli 2.3.0 and update to match new addon blueprint

### PR DESCRIPTION
**Pull request by SaladFork**
Updates `ember-cli` to `2.3.0` and updates the project to the updated addon blueprint.

This was done in three steps:
  * Update project per [instructions in release notes](https://github.com/ember-cli/ember-cli/releases/tag/v2.3.0)
  * Review changes in [the diff from the last major version](https://github.com/kellyselden/ember-addon-output/compare/v1.13.15...v2.3.0) and apply where possible
  * Re-apply the addon blueprint and review remaining changes

### CODE REVIEW

**Comment by listepo** [comment]
I am for to merge :+1:

**Comment by miguelcobain** [comment]
@listepo you're using the `wip/v1.0.0` branch?

**Comment by listepo** [comment]
@miguelcobain yes, I want to help

**Comment by miguelcobain** [comment]
Awesome!

**Pull request merged**
