### PR TITLE
Feature/new chips

### PR DESCRIPTION
**Pull request by mansona**
WIP to update the chips implementation

### CODE REVIEW

**Comment by mansona** [comment]
ok so @miguelcobain there are a lot of things going on with this PR. I think the best thing for us to do to progress is for us to identify what is wrong with the `wip/1.0` branch vs what is wrong with whatever I'm doing. 

When I run the demo app it looks like this: https://cloudup.com/cLDVNXnFTfY I thought it looks like the backdrop might be active but I'm not too sure. I checked it just on the `wip/1.0` branch and it is the same so I don't think it's something that I'm doing locally. 

I've also created this: https://github.com/miguelcobain/ember-paper/pull/268 because the current JQuery is breaking on that branch.

**Comment by miguelcobain** [comment]
Yes. Something is wrong on th wip branch. It happened when we pulled angular material sass styles.
Maybe we're not handling hue's, shadows, etc, correctly, @mike1o1 ?

**Comment by mansona** [comment]
Yea, so essentially the main blocker for me on this is that everything *seems* to be working, but the "delete chip" crosses aren't showing. I think it's best that we solve the **general** issues before I go into the specifics of why the crosses are missing. Do you think that is a good general strategy?

**Comment by miguelcobain** [comment]
> I think it's best that we solve the general issues before I go into the specifics 
Agreed, @mansona.

**Comment by miguelcobain** [comment]
@mansona, it looks like @mike1o1 has solved the color problems on the `wip/1.0` branch.

**Comment by mansona** [comment]
@miguelcobain yep, looing a lot better now :+1: 

My next issue is that the autocomplete component is pretty messed up at the moment: https://cloudup.com/cvbltmcbK3d that would be the next one of the "general issues" to deal with I think

**Comment by mansona** [comment]
@miguelcobain also do any of the paper-icons work for you? https://cloudup.com/ccE8tyTAra9

**Comment by mike1o1** [comment]
We aren't including any of the stylesheets for the icons, so none of them are working. Should we link to the material icon font stylesheet directly?

**Comment by miguelcobain** [comment]
icons should be working now.

**Comment by peec** [comment]
From research I have seen that autocomplete is changed, and now looks pretty messed up because of contents of the autocomplete is now placed within a new component named `md-virtual-repeat-container`. So we basically need to implement the md-virtual-repeat component and then fix autocomplete

**Comment by SaladFork** [comment]
Unfortunately GitHub doesn't seem to allow you to change the base branch you are PRing against and automatically closes any PRs when the base branch is deleted.

Moving forward [we are using the `master` branch for `1.0.0`](https://github.com/miguelcobain/ember-paper#version-roadmap) work so please feel free to open a new PR against `master` :)

**Comment by mansona** [comment]
@SaladFork can you re-open this please? I have rebased and pushed an update

**Comment by DanChadwick** [comment]
@mansona - Unfortunately you need to open another PR. In the "great merge", the wip/v1.0.0 branch was merged and deleted. This had the unfortunate side effect of closing all the PR's agains wip/v1.0.0 and there github doesn't seem to have a way to change the target branch. When you do, please reference this PR so we have history. It's a pain, I know. Thanks.

**Comment by mansona** [comment]
@DanChadwick https://github.com/miguelcobain/ember-paper/pull/344 🎉

**Pull request closed without merging**
