### PR TITLE
Upgrade eps@1.8.5

### PR DESCRIPTION
**Pull request by xomaczar**

### CODE REVIEW

**Comment by miguelcobain** [comment]
@xomaczar we should bump ember-basic-dropdown version as well, to the same version that eps uses, right?

**Comment by xomaczar** [comment]
Forgot about that -- absolutely.

**Comment by miguelcobain** [comment]
I'm concerned if this upgrade is just a matter of bumping versions. Please test if this upgrade breaks any functionality.

**Comment by xomaczar** [comment]
You don't trust our test suite?

**Comment by miguelcobain** [comment]
@xomaczar unfortunately some things are still poorly tested, e.g paper-select, only two tests there

**Comment by miguelcobain** [comment]
But overall, I think we have very good tests.

**Comment by xomaczar** [comment]
Upgrading to the latest ember-basic-dropdown breaks a bunch of things -- so
don't be concerned :), more fixes to come.

**Comment by bjornharrtell** [comment]
As I have personal interest in this upgrade and looked into upgrading but @xomaczar got there first with what looks like clean changes and nice removals of no longer needed code. Tried out the branch locally and tried the autocomplete, menu and select components without any issues. Great work @xomaczar! :)

**Comment by miguelcobain** [comment]
Great PR. 👌 
Thanks!

**Pull request merged**
