### PR TITLE
Blockless autocomplete

### PR DESCRIPTION
**Pull request by xomaczar**

### CODE REVIEW

**Comment by miguelcobain** [comment]
I think I see the point of this. We have to pass in `labelPath` anyway, so a blockless version might make sense.
I wish we could get rid of `labelPath`, but I don't think we can because of the input.

**Comment by xomaczar** [comment]
Agree, labelPath is only needed when binding to the list of objects. The blockless version should cover the 80% of all the use cases.

**Comment by xomaczar** [comment]
@miguelcobain  ^

**Comment by xomaczar** [comment]
Ping @miguelcobain

**Comment by miguelcobain** [comment]
I went ahead and added these changes myself.
Sorry for taking 2 years for something that makes total sense and is easy to review.

**Pull request closed without merging**
