### PR TITLE
Consistent SASS theme colors

### PR DESCRIPTION
**Pull request by wmadden**
For some reason the foreground colors are set during preprocessing to fixed values, making it impossible to alter them using SASS variables. This PR replaces the generated constants with SASS expressions, making it possible to override them, and strips dead code from `lib/angular-scss-filter.js`.

### CODE REVIEW

**Comment by wmadden** [comment]
@miguelcobain ping

**Comment by miguelcobain** [comment]
@wmadden sorry for the late reply. I had to do some changes to the filter and didn't know if they influenced this.
Can you please rebase and fix conflicts?

**Comment by wmadden** [comment]
@miguelcobain done

**Comment by miguelcobain** [comment]
@wmadden looks like the CI failed: https://travis-ci.org/miguelcobain/ember-paper/jobs/230832609

**Comment by wmadden** [comment]
Ah nuts 😞 I'll fix it later

**Comment by miguelcobain** [comment]
Here's an interesting regex AM itself is using: https://github.com/angular/material/blob/master/src/core/services/theming/theming.js#L889

**Comment by Falibur** [comment]
@wmadden hope that you will and can fix this 👍

**Comment by wmadden** [comment]
@miguelcobain I've fixed the issue on this branch but unfortunately the build is broken due to [this issue](https://github.com/yarnpkg/yarn/issues/3485) with Yarn and node-sass.

You've probably seen it before - locally it's fixed by running `npm rebuild node-sass`, after which the tests all pass. On CI it might be fixed by just rerunning the build and clearing the cache, I'm not sure, but you'll probably see the same failure on master.

**Comment by jiaweihli** [comment]
You can also add `npm rebuild node-sass` to CI after updating npm dependencies - this should fix it.

There a few suggestions floating around to add this to the `postinstall` script in `package.json`, but IIRC this was buggy in some situations (may have been fixed since).

**Comment by wmadden** [comment]
@miguelcobain looks like this issue is fixed in https://github.com/miguelcobain/ember-paper/pull/709

**Comment by miguelcobain** [comment]
#709 is not ready to merge. It still has issues (only #705)

**Comment by miguelcobain** [comment]
I added the workaround for the yarn bug on master. This PR looks like it simplifies things a lot while providing more flexibility as well. 👍

**Comment by wmadden** [comment]
Nice work @miguelcobain, looks like the build is passing now 👍

**Comment by Falibur** [comment]
Nice work you all :thumbsup:

**Comment by v3ss0n** [comment]
Nice !!! that is awesome!

**Pull request merged**
