### PR TITLE
Add paper-card title components

### PR DESCRIPTION
**Pull request by baileymiller182**
Adds a few components to expand potential layouts of `paper-card` by providing analogs of the card title components found in Angular Material (https://material.angularjs.org/latest/demo/card):

- paper-card-title: Can be used in place of, or in conjunction with, paper-card-content to display card title text and images.
- paper-card-title-text: Displays some title text.
- paper-card-title-media: Displays a title image in the upper right corner of the card.

Example:
```handlebars
{{#paper-card class="card-lg-media-demo"}}
  {{#paper-card-title}}
    {{#paper-card-title-text}}
      <h2>Paracosm</h2>
      <p>The titles of Washed Out's breakthrough song and the first single from Paracosm share the...</p>
    {{/paper-card-title-text}}
    {{#paper-card-title-media}}
      <img class="md-media-lg" src="washedout.png">
    {{/paper-card-title-media}}
  {{/paper-card-title}}
  <div class="md-actions" layout="row" layout-align="end center">
    {{#paper-button}}Action 1{{/paper-button}}
    {{#paper-button}}Action 2{{/paper-button}}
  </div>
{{/paper-card}}
```

Would produce the following (from updated docs)

image

### CODE REVIEW

**Comment by miguelcobain** [comment]
Looks good, @baileymiller182 

We just need to update the template snippet at `tests/dummy/app/templates/card.hbs` and add a changelog entry.

Can you please do it?

**Comment by baileymiller182** [comment]
@miguelcobain Sure, this is done.

**Comment by miguelcobain** [comment]
@baileymiller182 `0.2.11` is released. The changelog entry would have to be under a `#master` version, for example.

**Comment by baileymiller182** [comment]
:+1:

**Comment by miguelcobain** [comment]
Thanks!

**Pull request merged**
