### PR TITLE
Update ember-cli-sass to v6 (node-sass 4.1.0)

### PR DESCRIPTION
**Pull request by xomaczar**

### CODE REVIEW

**Comment by xomaczar** [comment]
This should allow us to run in twiddle

**Comment by v3ss0n** [comment]
wow nice we can twiddle with ember-paper now ??

**Comment by miguelcobain** [comment]
Would be great to do so!

**Comment by miguelcobain** [comment]
We're not using any sass from eps or ebd, but I'm not sure if those need to be updated as well.

**Comment by xomaczar** [comment]
I know - maybe PRs to both

**Pull request merged**
