### PR TITLE
[FEATURE] Add onInvalid action to form.

### PR DESCRIPTION
**Pull request by Serabe**
Add `onInvalid` action, invoked when trying to submit an invalid form.

### CODE REVIEW

**Comment by miguelcobain** [comment]
Very weird. I can merge this because it's clearly not related.

Regarding the PR, I love the idea, but I'm unsure about the naming.
`onInvalid` sounds like an action the is sent when the form becomes invalid, which is not the case.

What if we kept using `onSubmit` but we sent the validity of the form in the action?
People could then later treat the submit accordingly in their action.

Using your approach, I think we should rename the action. Perhaps `onSubmitInvalid`?

Let me know your thoughts. Thanks for the PR.

**Comment by Serabe** [comment]
I would like to use `invalid` as the name of the event because [that is the standard name according to MDN](https://developer.mozilla.org/en-US/docs/Web/Events/invalid). If you don't like that option, `onSubmitInvalid` looks good too.

**Comment by miguelcobain** [comment]
I was unaware of that event.
Makes sense to name this action accordingly since they attempt to do the same thing.
Thanks again!

**Comment by Serabe** [comment]
Thanks!

**Comment by Serabe** [comment]
@miguelcobain is there any planned release that includes this PR?

Thanks!

**Comment by miguelcobain** [comment]
@Serabe `v1.0.0-beta.4` was published with this PR. Sorry for the delay.

**Comment by Serabe** [comment]
Thanks!

**Pull request merged**
