### PR TITLE
removed action handlebars helper and replaced it a click event handler inside js

### PR DESCRIPTION
**Pull request by agarcia17**
Fixes issue with action helper not passing the event object

### CODE REVIEW

**Comment by agarcia17** [comment]
if you go to the demo page and expand one of the menus that has a submenu you will see the bug in the console: 'Uncaught TypeError: Cannot read property 'stopPropagation' of undefined because the event object was never being passed in

**Comment by miguelcobain** [comment]
Any idea why tests are failing?

**Comment by dustinfarris** [comment]
Should rebase to get CI fixes from master

**Comment by agarcia17** [comment]
@dustinfarris thanks! :)

**Comment by miguelcobain** [comment]
thanks @agarcia17 !

**Pull request merged**
