### PR TITLE
Pass item through as expected rather than label

### PR DESCRIPTION
**Pull request by kat3kasper**

### CODE REVIEW

**Comment by miguelcobain** [comment]
Thank you for the PR!
Can you please add a new CHANGELOG entry under a new version named master?

**Comment by kat3kasper** [comment]
@miguelcobain I believe this is what you are asking for

**Comment by miguelcobain** [comment]
Perfect. Thanks.

**Comment by miguelcobain** [comment]
@kat3kasper if you're using ember-paper, we may need your help :)

Join us at #e-paper in ember's slack. :+1:

**Pull request merged**
