### PR TITLE
Add addons page to demo

### LINKED ISSUE #652: Consider an addon/plugins section for third party ember-paper addons
It could be beneficial to have a section on the docs page with links to addons made for ember paper e.g

- https://github.com/CoachLogix/ember-paper-selection-dialog

- https://github.com/CoachLogix/ember-paper-swiper

It could encourage others to make their custom ember-paper components public too.
For example I have a paper-autocomplete component that gets addresses from google places api which could be re used.

EDIT: List of known addons:

https://github.com/CoachLogix/ember-paper-selection-dialog
https://github.com/CoachLogix/ember-paper-swiper
https://github.com/CoachLogix/ember-paper-stepper
https://github.com/miguelcobain/ember-paper-expansion-panel
https://github.com/ibarrick/paper-data-table
https://github.com/Subtletree/ember-paper-link
https://github.com/cogniteev/ember-paper-tabs (will be moved into core at some stage)
https://github.com/NLincoln/ember-paper-dual-slider

### PR DESCRIPTION
**Pull request by Subtletree**
Draft of the 'extensions' demo page. Settled on the name extensions instead of addons to prevent confusion with ember addons in general.

Threw together the wording etc pretty quick so any changes are welcome

screen shot 2017-06-06 at 12 59 59 pm

closes #652

### CODE REVIEW

**Comment by v3ss0n** [comment]
This should be ok to merge.

**Comment by miguelcobain** [comment]
@Subtletree Thanks a lot for this!

Can we use "Addon" terminology instead of "Extensions"? I think "extensions" might cause some confusion in the ember world.

**Comment by panthony** [comment]
Not sure including `paper-tabs` is worth it:

- it's temporary and should be included in core
- it's buggy with the latest angular version (:sob:)

**Comment by v3ss0n** [comment]
i agree , since `paper-tabs` is planned to merge into core

**Comment by Subtletree** [comment]
sweet, should be good to go

**Comment by miguelcobain** [comment]
Thanks a lot and sorry for the delay.

**Pull request merged**
