### PR TITLE
Feature: fab-buttons & fab-speed-dial / tooltips

### PR DESCRIPTION
**Pull request by chrisitananese**
Demo: http://chrisitananese.github.io/ember-paper/#/fab-speed-dial

* Full features work
* Angular scss
* Animations work

```handlebars
{{#paper-fab-speed-dial direction="down" animation="scale" warn=true}}

      {{#paper-button fab=true}}{{paper-icon icon="android"}}{{/paper-button}}
      {{#paper-button fab=true}}{{paper-icon icon="person"}}{{/paper-button}}
      {{#paper-button fab=true}}{{paper-icon icon="message"}}{{/paper-button}}

{{/paper-fab-speed-dial}}
```

### CODE REVIEW

**Comment by peec** [comment]
Very nice, :+1:

**Comment by chrisitananese** [comment]
Added tooltip component. Demo: http://chrisitananese.github.io/ember-paper/#/tooltip

Everything works excepts the animation.

@peec I tried to use your addon as I did for the fab-speed-dial, but wasn't quite sure how to use it.

I set my transitionClass to md-show so the addon looks for the classes .md-show-enter.md-show-enter-active and same for leave, but in the scss instead of enter and leave they use add and remove.

Got quite confused trying to figure it out so sorry for the vague description.

**Comment by peec** [comment]
@chrisitananese I see what you mean, I will have to make support for custom "add" / "remove" classes so that it's possible to use "show" / "leave" instead of "add" / "remove". Ill post back when, then you can update the npm dependency afterwards.

**Comment by jamesdixon** [comment]
@chrisitananese nice work! I just tested the tooltip on mobile safari and it does appear there are some positioning issues with regards to the tooltip itself.

**Comment by chrisitananese** [comment]
Thanks for testing @jamesdixon 
Which version of safari did you use? Will try to fix it these days.

**Comment by jamesdixon** [comment]
No problem, @chrisitananese!

I'm using mobile safari on iOS 8.4.1. I also have an iOS 7.1.2 device I can test on as well when I get a chance depending on what you want to support.

**Comment by chrisitananese** [comment]
Tested in iPad with Safari on 8.4 to and seems to work fine.
image

**Comment by jamesdixon** [comment]
I just checked it again. I think it had something to do with me tapping on the radios to change the position of the tooltip. When doing that, things start getting a bit haywire.

**Comment by jamesdixon** [comment]
Just interacting with the speed dial, it did seem to work just fine.

**Comment by chrisitananese** [comment]
Ok, checkd on iphone to, just to be sure but worked fine.

**Comment by jamesdixon** [comment]
Did you see any weirdness when tapping on the radio buttons? I'm still seeing weird things happen when doing that.

**Comment by chrisitananese** [comment]
No not really, mybe you meen that the tooltips are fading in from the top left corner and not from the button it self as on angular-material.
Thats because the animation is still missing.

**Comment by chrisitananese** [comment]
Will move move both features to differrent branches and then close this PR as there are to many unrelated commits in here.

**Comment by jamesdixon** [comment]
Any idea when this may be merged?

**Comment by chrisitananese** [comment]
I've been busy lately at woirk so I still didn't moved them in two different branches. As soon it's done I'll make a PR for each of the features.

**Pull request closed without merging**
