### PR TITLE
General accessibility enhancements

### PR DESCRIPTION
**Pull request by peec**
This PR adds general accessibility for checkbox and switch components.

- add correct `role="checkbox"` to checkbox and switches. 
- add `aria-label` to checkbox and switch when label attribute is present. 
- Tabbing between checkboxes and switches gives a nice visual effect like angular material does.
- **switch:** Allow to use space to turn switch on/off. 
- **list controls**: Hover effect and focus effects on corresponding buttons. ( This gives the side menu a nice touch).

Source of implementation:
https://material.angularjs.org/latest

### CODE REVIEW

**Comment by miguelcobain** [comment]
Two things:
- What's the problem with tabbing through the menu items? I believe that is expected. The flaw here is that there is no visual feedback. That may be fixed by #106 
- Can we use the constant for `KEY_CODE_SPACE` in utils?

**Comment by peec** [comment]
@miguelcobain 

> What's the problem with tabbing through the menu items? I believe that is expected. The flaw here is that there is no visual feedback. That may be fixed by #106

You are correct, I initially thought it was like that but after checking angular material I see that they can tab through menu items.

> Can we use the constant for KEY_CODE_SPACE in utils?

Added constants in checkbox and switch.

**Comment by miguelcobain** [comment]
I'm currently a bit busy, but I promise to review all these PR very very soon.
Many thanks!

**Comment by peec** [comment]
This is too outdated for now, I'll create a new PR for this soon. Closing this for now.

**Pull request closed without merging**
