### PR TITLE
New feature: paper-tabs (rebased from @mellatone)

### PR DESCRIPTION
**Pull request by fewstera**
I have taken the work done by @mellatone and rebased it against master as per the discussion in #312.

I hope this gets the ball rolling again for adding tab support.

### CODE REVIEW

**Comment by rwwagner90** [comment]
Thanks for doing the rebase @fewstera! Looks like travis is failing though 😞

**Comment by SirZach** [comment]
@fewstera this looks great!! can't wait to see this guy merged in!

**Comment by mellatone** [comment]
@fewstera You are awesome!

**Comment by fauda** [comment]
Bumping, would be great to have this

**Comment by xomaczar** [comment]
We need someone to take ownership

**Comment by mellatone** [comment]
@miguelcobain ping on my previous comment. I'm ready to pick this up once I have more direction.

**Comment by xomaczar** [comment]
What's remaining code review? Integration tests? Compare functionality vs AM tabs? I can do initial code review today/tomorrow.

**Comment by mellatone** [comment]
@xomaczar Basically it comes down to whether we want to fix the broken tests and merge current functionality as-is, or achieving full feature-parity with the AM tabs first.

**Comment by xomaczar** [comment]
Based on your previous comments tests are broken on ember@2.9. Or at the time of writing it was 2.8 - I am on mobile so haven't yet looked at travis logs.

**Comment by xomaczar** [comment]
Can we get a checklist of things that you know are still broken

**Comment by Luiz-N** [comment]
would love this merged in!

**Comment by omerjerk** [comment]
Please don't let this pull request die as well. :(

**Comment by miguelcobain** [comment]
Closed in favor of https://github.com/miguelcobain/ember-paper/pull/590

**Pull request closed without merging**
