### PR TITLE
Allow tooltips in icons

### PR DESCRIPTION
**Pull request by Subtletree**

### CODE REVIEW

**Comment by miguelcobain** [comment]
Very useful!
Just trying to understand why the tests failed.

**Comment by Subtletree** [comment]
😕  had them all passing locally

**Comment by miguelcobain** [comment]
Yes, they're passing locally too.
Restarted the build. Let's see.

**Comment by miguelcobain** [comment]
Meanwhile, it would be awesome if you could add a changelog entry. If not, I can do it tomorrow.

**Comment by Subtletree** [comment]
Cool, I'm on it

**Comment by miguelcobain** [comment]
I'm merging this since it is clearly unrelated. Thanks again!

**Pull request merged**
