### PR TITLE
Chips: Add missing mouse interactions

### PR DESCRIPTION
**Pull request by pauln**
Add the ability to click anywhere in the chips element to give the input focus, plus the ability to click on a chip to focus it.  This makes the chips element behave more like its Angular Material counterpart, which supports these interactions.

### CODE REVIEW

**Comment by wmadden** [comment]
@miguelcobain / maintainers is there any progress here? `paper-chips`'s behaviour is at the moment pretty unusable

**Comment by pauln** [comment]
@miguelcobain I've just rebased this onto current master, as there was a conflict.  The Travis checks appear to be failing due to an issue with `node-sass` :
`ENOENT: no such file or directory, scandir '/home/travis/build/miguelcobain/ember-paper/node_modules/node-sass/vendor'`

I see that's fixed in PR #709, so this build should pass once that's been merged.

**Comment by pauln** [comment]
@miguelcobain I've rebased this again now that the fix for the `node-sass` CI issue is on master, and the Travis checks are passing again.  #615 and #632 are still showing no conflicts, so all should now be good to go again, when you get a chance.

**Comment by pauln** [comment]
- Rebased again
- Fixed issues with focus being left behind on autocomplete and contact chips elements
- Fixed incomplete mouse interactions on contact chips

**Comment by miguelcobain** [comment]
@pauln thanks your fixes look great.
There are two more things left that I could identify, though.

1. when `readOnly` is true, we shouldn't be focusing chips.
2. when `readOnly`is true, we should add the `md-readonly` class on the `<md-chips-wrap>` element.
3. `<md-chips>` *incorrectly* has the class `md-chips`. `<md-chips-wrap>` should have that class instead.

Last two problems make the style `cursor: text` enabled, even when the control is readOnly. This leads to a confusing situation where you seem to be able to click the control, but you aren't.

**Comment by pauln** [comment]
Oops - well spotted, @miguelcobain.  Those issues should now be resolved.

**Comment by miguelcobain** [comment]
@pauln :1st_place_medal:

**Pull request merged**
