### PR TITLE
Ember Textsupport for paper-text

### PR DESCRIPTION
**Pull request by benedikt-d**

### CODE REVIEW

**Comment by benedikt-d** [comment]
I guess it failed because glimmer is not working :-(

**Comment by miguelcobain** [comment]
This was more difficult than it appears to.
Bubbling arbitrary actions from a sub component isn't easy.

**Comment by benedikt-d** [comment]
Yes just noticed i forgot half the code :-) I'm on it...

**Comment by benedikt-d** [comment]
Wondering if we would need something like target in the paper button.

**Comment by miguelcobain** [comment]
I found this: https://gist.github.com/fotinakis/dbb33b5418b9561e8d31

But we still need to handle `focus-in` and `focus-out` inside out paper-button to set `focus` property.
I was trying to avoid to write all action handlers and just bubble them manually.

**Comment by benedikt-d** [comment]
Hm not quite working. When focusing:
Uncaught TypeError: Cannot read property 'get' of null
Uncaught TypeError: Cannot read property 'set' of null

**Comment by benedikt-d** [comment]
I don't quite understand what base focusable does in this case? And also why `this.set('focus',true);`is called twice once in base focusable and once in paper-text. The problem seems to be that the values of pressed and focus are null when these methods are called directly. Don't know how exactly I can avoid that.

**Comment by benedikt-d** [comment]
Put the sendAction into the base-focusable mixin as this can be useful for other components as well. I think it should be ready now.

**Comment by benedikt-d** [comment]
If one of those new other methods are useful for other components they can be moved there too I guess.

**Comment by benedikt-d** [comment]
This solution causes problems with other components which use base-focusable...
Cannot read property 'set' of null
Maybe someone has some good advice on how to fix it.

**Pull request closed without merging**
