### PR TITLE
Bind-attr and hasBlock deprecation fixes

### PR DESCRIPTION
**Pull request by brianmbutler**

### CODE REVIEW

**Comment by miguelcobain** [comment]
Two problems:
1. Like Travis shows us, the tests fail in ember-beta
2. There other places we use `{{#if template}}`

**Comment by brianmbutler** [comment]
Yeah I need to rebase and squab and look at the fall back to pre-glimmer.   In 1.13+ I think you can just yield

**Comment by miguelcobain** [comment]
I see you've made changes like from this
```hbs
<label {{bind-attr for=inputElementId}}>{{label}}</label>
```
to
```hbs
<label>{{label}}</label>
```

This will make attribute bindings go way. I think we should use the new syntax:
```hbs
<label for="{{inputElementId}}">{{label}}</label>
```

**Comment by brianmbutler** [comment]
I can fix that up today.  I've seen other components who declare the bound attrs in the component.js but then just {{yield}} but I suppose then you have to declare it in your template like  {{#foo inputElementId=inputElementId}}.

Right?

**Comment by miguelcobain** [comment]
That's right.

**Comment by miguelcobain** [comment]
Fixed deprecations on master. Thanks.

**Pull request closed without merging**
