### PR TITLE
Paper tabs rebased

### PR DESCRIPTION
**Pull request by mellatone**

### CODE REVIEW

**Comment by mellatone** [comment]
Resolved merge conflicts. Will take a look at the failing tests as soon as travis is done.

**Comment by miguelcobain** [comment]
Something must be wrong here. I don't see anything tab-related in the PR changes.

**Comment by mellatone** [comment]
@miguelcobain You're right. The pull from @fewstera's branch didn't go through. See my latest commit.

**Comment by mellatone** [comment]
And the failing tests are in 👍

**Comment by fewstera** [comment]
I'm not sure if you want the commit c15ed0a. That was used for my project which had to work offline.

**Comment by mellatone** [comment]
Lol, I thought local fonts had just finally been addressed. I will probably back that out until we can agree on an approach for addressing offline fonts.

**Comment by miguelcobain** [comment]
Yes. This PR includes a different way of adding fonts. We should tackle that in another place.

**Comment by panthony** [comment]
any chances to see this PR merged fairly soon once the font issue is resolved ? I'll need a tab component and I'd rather give use that 👍

**Comment by miguelcobain** [comment]
Closed in favor of https://github.com/miguelcobain/ember-paper/pull/578

**Pull request closed without merging**
