### PR TITLE
Uncomment paper-menu positioning for top/bottom and left/right

### PR DESCRIPTION
**Pull request by DanChadwick**
This allows the current paper-menu to be used for drop-down menus (of a sort).

### CODE REVIEW

**Comment by miguelcobain** [comment]
@peec Do you have any idea of why that was commented? o.O

**Comment by DanChadwick** [comment]
It appears to have been written as part of a port, in anticipation of a toolbar component, which hasn't been finished yet. Using this positioning is very useful for creating something close to an toolbar, but with icons. The biggest difference is that going from one menu to another requires two clicks -- the first to close one menu and the second to open another. While I'm waiting for the toolbar component, I'm satisfied with that behavior, and would love to see this positioning incorporated into the master (or WIP) branch.

**Comment by DanChadwick** [comment]
Thank you *very* much for your dedication and contribution. I am very grateful. :+1:

**Comment by miguelcobain** [comment]
You're welcome. :)

**Pull request merged**
