### PR TITLE
Support for engines

### PR DESCRIPTION
**Pull request by enniel**
Add support for ember-engines. With lazy loading yet not worked.

### CODE REVIEW

**Comment by miguelcobain** [comment]
I have moved the templates from the `app` to `addon` folder in master.
Can you rebase?

I see you're pulling dependencies from npm now. That's very desirable.
Have you considered using [ember-cli-node-assets](https://github.com/dfreeman/ember-cli-node-assets)? It provides a nice abstraction on the npm import story.
Example: https://github.com/miguelcobain/ember-sticky/blob/master/index.js#L8-L17

**Comment by knownasilya** [comment]
@enniel which version of engines did you test against for lazy support?

**Comment by knownasilya** [comment]
@John0x see if you can try this PR. It works for me. Just make sure to share the `-document` service to your engine.

**Comment by knownasilya** [comment]
@miguelcobain this is ready I think. Seems to work with lazyloaded engines too.

**Comment by miguelcobain** [comment]
I'm just concerned that prism was removed from bower. Either ember-prism includes prism from npm or the conde highlighting stopped working in the demo app.

**Comment by John0x** [comment]
This PR works for me too, would be great to see it being merged.

**Comment by miguelcobain** [comment]
Thanks to the missing in action @enniel starting this. :D
Thanks to @knownasilya @John0x and @mellatone for helping to test this.
This was merged and released. Have fun.

**Pull request merged**
