### PR TITLE
Adding Snackbar to Ember paper

### PR DESCRIPTION
**Pull request by henrixapp**
+ GestureMixin for swipe-detection
+ paper-snackbar-inner
+ paper-snackbar-text
+ Demo app
TODO: tests

### CODE REVIEW

**Comment by miguelcobain** [comment]
@henrixapp thank you for your contribution!

We imagined toast support in an RFC: https://github.com/miguelcobain/ember-paper/issues/706

Also, we include hammer js which should be more than enough for gesture support. No need to port anything for that.

And I think paper-toast is the standard name AM uses.

**Comment by henrixapp** [comment]
Yes, probably the name should be paper toast, because it does not strictly follow the rules of a snackbar. I tried to follow #706 during implementation :grin:. I did not notice hammerjs, so I ported the angular implementation. Should I rename it?

**Comment by miguelcobain** [comment]
Yes, please.

**Comment by henrixapp** [comment]
Should it yield the button, because it only adds `accent=true` by default?

**Comment by miguelcobain** [comment]
This doesn't include the service mentioned in the rfc, correct?

**Comment by henrixapp** [comment]
Yes. Didn't have time to implement that yet.

**Comment by henrixapp** [comment]
What's missing:

- [ ]  Tests
- [ ] Animation
- [ ] Service

Have you any ideas for animations?

**Pull request closed without merging**
