### PR TITLE
make ripple touch events passive

### PR DESCRIPTION
**Pull request by xomaczar**
Improves scrolling and fixes warnings

### CODE REVIEW

**Comment by Subtletree** [comment]
closes #870 

Good catch with the feature detection 👍.  Looks like we might need:
```
let options = supportsPassiveEventListeners ? { passive: true } : false;
```
instead of the empty object https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection

**Comment by xomaczar** [comment]
@Subtletree thanks for the code review, sorry I did not see that there was an open PR handling similar use case. I've updated my PR with your suggestions.

**Comment by xomaczar** [comment]
^ @miguelcobain

**Comment by miguelcobain** [comment]
Indeed, the feature detection is needed to correctly use passive events.
Thank you both @xomaczar and @Subtletree.

**Pull request merged**
