### PR TITLE
Feature/snackbar

### PR DESCRIPTION
**Pull request by mellatone**
Continues the work started in #722
Adds tests for RFC #706

### CODE REVIEW

**Comment by xomaczar** [comment]
+1

**Comment by henrixapp** [comment]
Are you planning to implement the service? I think, we should  have the possiblity to create a simple toast with button.

**Comment by miguelcobain** [comment]
Yes. We're developing that. Should be merged on monday/tuesday.

A domingo, 16/07/2017, 13:18, henrixapp <notifications@github.com> escreveu:

**Comment by henrixapp** [comment]
When will this published to npm?

**Pull request merged**
