### PR TITLE
update install instructions to match ember-cli updates

### PR DESCRIPTION
**Pull request by tikotzky**

### CODE REVIEW

**Comment by alexlafroscia** [comment]
You might want to update the [text on the main page of the "dummy" app](https://github.com/miguelcobain/ember-paper/blob/master/tests/dummy/app/templates/index.hbs#L21) too, since that is what the Github Pages site uses.

**Comment by miguelcobain** [comment]
ping @tikotzky

**Comment by tikotzky** [comment]
done.

**Comment by miguelcobain** [comment]
Thanks.

**Pull request merged**
