### PR TITLE
Fix deprecation toc arguments in component lifecycle hooks

### PR DESCRIPTION
**Pull request by bjornharrtell**
See https://emberjs.com/deprecations/v2.x/#toc_arguments-in-component-lifecycle-hooks.

~~~Depends on #690.~~~

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Rebased.

**Comment by bjornharrtell** [comment]
Rebased once more without dependency on #690.

**Comment by ibarrick** [comment]
We might consider using this as well
https://github.com/workmanw/ember-diff-attrs

**Comment by bjornharrtell** [comment]
This is also fixed with https://github.com/miguelcobain/ember-paper/pull/726 which I hope will get merged soon. Closing this.

**Pull request closed without merging**
