### PR TITLE
fix(ac): don't use paper-autocomplete _innerText

### PR DESCRIPTION
**Pull request by xomaczar**

### CODE REVIEW

**Comment by xomaczar** [comment]
Fixes #932 #935

**Comment by xomaczar** [comment]
cc @pauln @miguelcobain

**Comment by xomaczar** [comment]
@pauln can you review

**Comment by miguelcobain** [comment]
Anything else needed here?
This LGTM!

**Comment by xomaczar** [comment]
Not that I know of

**Pull request merged**
