### PR TITLE
Match paper-sidenav width with AM@1.0.6

### PR DESCRIPTION
**Pull request by xomaczar**

### CODE REVIEW

**Comment by miguelcobain** [comment]
Nice!
The sidenav size is indeed smaller like in AM docs. But the scrollbars look different for me. Can you confirm that?

I'd like to understand why.

**Comment by xomaczar** [comment]
Yes the webkit browsers will have different scrollbars. You don't like 'em?

**Comment by xomaczar** [comment]
They kind of compliment the md style, nah? I am on ubuntu & chrome my scrollbars take away from this polished ember-paper demo ui.

**Comment by miguelcobain** [comment]
@xomaczar i meant that with this PR I'm seeing different scrollbars from the angular material website. Can you confirm that?

**Comment by xomaczar** [comment]
I confirm - I changed it on purpose

**Comment by xomaczar** [comment]
And this is not part of AM

**Comment by miguelcobain** [comment]
I think I didn't make myself clear.

Angular Material (1.0.6) scrollbar:
screen shot 2016-09-10 at 00 34 27

this PR's scrollbar:
screen shot 2016-09-10 at 00 34 33


Why are they different? This was my initial question.

**Comment by xomaczar** [comment]
Cause I did not like how the native scrollbars looked in chrome/Firefox on ubuntu/windows. I can remove the scrollbars styles ...

**Comment by miguelcobain** [comment]
I'm not opposed to any scrollbar in particular. I'm just trying to understand.

But doesn't this PR include the same styles as AM? That was my understanding. If it includes, why are they different?

**Comment by xomaczar** [comment]
Yes this PR includes some of the AM demo/docs style - specifically width of the nav container - I added my scrollbar styles to further enhance demo app. I have no problem removing the scrollbar styles - to match am demo. Sorry for the confusion...

**Comment by miguelcobain** [comment]
Ah, ok. I thought these were scrollbar styles from AM. Didn't understand why the scrollbars were different. Got it. :)

**Comment by xomaczar** [comment]
What are we doing with this PR?

**Comment by miguelcobain** [comment]
Merging. :)

**Comment by xomaczar** [comment]
Done... :)

**Pull request merged**
