### PR TITLE
Allows you to use the html5 download attribute

### PR DESCRIPTION
**Pull request by devotox**
This especially works well with data URIs

### CODE REVIEW

**Comment by miguelcobain** [comment]
Thanks. 👍

**Comment by devotox** [comment]
It's  my pleasure. Question... There is no way to change a tagName after
init is there?

**Comment by miguelcobain** [comment]
There isn't. It's an ember restriction. You have some problem related with that?

**Comment by devotox** [comment]
Not exactly I worked around it. I just noticed it when I was making this
PR. Since my href attribute came dynamically after render the component
remained a button I then tried didUpdateAttrs and realized it was not
possible but had never explicitly read that anywhere. Just wanted to
clarify my findings. Easy workaround was to set a default href and then
change it when I got the new value.

**Pull request merged**
