### PR TITLE
Don't show dropdown if paper-autocomplete has a selected value and

### PR DESCRIPTION
**Pull request by xomaczar**
receives a focus.

### CODE REVIEW

**Comment by xomaczar** [comment]
@miguelcobain - should be all fixed.

**Comment by miguelcobain** [comment]
@xomaczar here are my thoughts:
We shouldn't force the user to provide both `onSearchTextChange` **and** `onSelectionChange`. The reason is that the searchText or selection may not be relevant to the user at all.

- [ ] we should assert that either `onSearchTextChange` or `onSelectionChange` is present
- [ ] if `onSearchTextChange` is absent, the input text should be updated normally as you type. Implementing this will probably lead to an internal property that holds the current input text?
- [ ] if `onSelectionChange` is absent, don't do anything?
- [ ] in both cases, `searchText` or `selected` should **never** be updated directly, otherwise the default two-way nature of bindings would propagate changes up (violating DDAU, hence the reason for an internal property)
- [ ] I think we can rename `onSearchTextChange` to `onTextChange`

**Comment by xomaczar** [comment]
- [x] assert that either onSearchTextChange or onSelectionChange is present
- [x]  if onSearchTextChange is absent, the input text should be updated normally as you type. Implementing this will probably lead to an internal property that holds the current input text?
- [x]  if onSelectionChange is absent, don't do anything?
- [x] in both cases, searchText or selected should never be updated directly, otherwise the default two-way nature of bindings would propagate changes up (violating DDAU, hence the reason for an internal property)
- [ ]  I think we can rename onSearchTextChange to onTextChange

**Comment by xomaczar** [comment]
@miguelcobain ready for review

**Comment by miguelcobain** [comment]
🎉 
very nice.

**Pull request merged**
