### PR TITLE
Fix paper-autocomplete value being overriden when changed

### LINKED ISSUE #1043: paper-autocomplete searchText is overriden on input
Hi,

I'm using the latest v1.0.0-beta21 and I have an issue with autocomplete.

Whenever I type something in the autocomplete, it doesn't show me what I type. The second character override the first one so the search is always using 1 character ...

Does anyone got that one ?

Using Ember 3.7 (and 3.6 before).

### PR DESCRIPTION
**Pull request by xtagon**
Fixes #1043

### CODE REVIEW

**Comment by xtagon** [comment]
I tried to add a new test for this scenario but wasn't able to get it to reproduce in a test. I did verify in my own app that it's no longer affected after this change, and the existing tests passed.

Thanks! 👍

**Comment by xtagon** [comment]
Anything holding this back from being merged?

**Comment by miguelcobain** [comment]
@xtagon sorry for taking so long to merge this. Thank you!

**Comment by miguelcobain** [comment]
@xtagon can you please retest if this bug persists on beta.26?

Basically this fix introduced a new bug. We were barking at the wrong door. The bug was somewhere else.

**Comment by xtagon** [comment]
Good catch, I will have a chance to test it in the next few days.

**Comment by xtagon** [comment]
@miguelcobain beta.26 looks good to me

**Pull request merged**
