### PR TITLE
proposed solution for #193

### PR DESCRIPTION
**Pull request by zkwentz**
Proposal for a solution to override, and add to, color palette colors. Not necessarily ready for merge.

### CODE REVIEW

**Comment by DanChadwick** [comment]
The failures appear to be unrelated to this PR.

**Comment by afomi** [comment]
This PR is very similar to https://github.com/miguelcobain/ember-paper/pull/250

**Comment by zkwentz** [comment]
@afomi there's a notable difference, in this PR, you can add named color sets to the color palette as well, by using `merge` in the `color` function.

**Comment by DanChadwick** [comment]
@zkwentz -- Excellent point. Maybe #250 should be closed in favor of this PR. It would be good to get this put to bed, unless there is some downside I don't understand.

**Comment by DanChadwick** [comment]
The test failures seem to be unrelated to this PR. Any chance we could get this committed? I can't see any downside, and it greatly improves the ability to tweak the MD designs.

**Comment by miguelcobain** [comment]
> Proposal for a solution to override, and add to, color palette colors. **Not necessarily ready for merge.**

Don't know what @zkwentz was talking about when he mentioned this.

I agree with @DanChadwick. This won't make breaking changes and as such will be merged. Please reopen if something's missing.

Thanks.

**Comment by zkwentz** [comment]
Awesome @miguelcobain, done. :+1:

**Comment by DanChadwick** [comment]
I'm not sure what the roadmap is for merging the 1.0/WIP branch back into master. If it's going to be a while, maybe it makes sense to merge this commit into the WIP branch, since it is a new feature, rather than a bug fix.

**Comment by DanChadwick** [comment]
This functionality has been incorporated into the wip/v1.0.0 branch, scheduled to become master very soon.

**Pull request closed without merging**
