### PR TITLE
Make predefined color palette overwritable

### PR DESCRIPTION
**Pull request by robinboening**

### CODE REVIEW

**Comment by afomi** [comment]
This looks reasonable to me. Not sure why the specs are failing for this though.

**Comment by DanChadwick** [comment]
This can be closed now. Fixed in PR #301.

**Comment by DanChadwick** [comment]
@miguelcobain: This can be closed now.

**Comment by miguelcobain** [comment]
@DanChadwick #301 was merged on `wip/v1.0.0`. This is a PR to the master branch.

**Pull request closed without merging**
