### PR TITLE
feat(inspector): register with ember inspector

### PR DESCRIPTION
**Pull request by xomaczar**
Registers ember-paper version with ember-inspector (Ember Inspector/Info)

ember-paper-inspector-version

### CODE REVIEW

**Comment by xomaczar** [comment]
Test failure is unrelated.

**Comment by miguelcobain** [comment]
Very cool! Thanks.

**Comment by xomaczar** [comment]
Can you build/deploy the new dummy app?

**Comment by xomaczar** [comment]
Thx

**Pull request merged**
