### PR TITLE
fab-speed-dial: new component implemenation

### PR DESCRIPTION
**Pull request by christiananese**
Demo: http://chrisitananese.github.io/ember-paper/#/fab-speed-dial
- [x] angular material scss only
- [x] added fab option to paper-button
- [x] fling animation
- [x] scale animation

### CODE REVIEW

**Comment by miguelcobain** [comment]
- fix typo "Absolut" to "Absolute"
- add changelog entry for next patch version

Looks great! Need to review a bit more in depth.

**Comment by chrisitananese** [comment]
Should be fine now.

**Comment by jamesdixon** [comment]
looks great @chrisitananese ! Excited to give this a shot once it's merged.

**Comment by jamesdixon** [comment]
@chrisitananese any chance on getting this merged soon?

**Comment by chrisitananese** [comment]
No idea @jamesdixon ,I think @miguelcobain wanted to review this before merging. Since my last commit, travis-ci seems to fail for ember-beta, I'll fix that these days.

**Comment by jamesdixon** [comment]
loud and clear. thanks @chrisitananese

**Comment by xomaczar** [comment]
@miguelcobain what's the status of this PR, can it be merged?

**Comment by miguelcobain** [comment]
@chrisitananese Sorry for asking you this.

Right now our main goal is to hit 1.0, since angular material hit 1.0 as well. Their components should be more stable from now on.
Could you please make this conform #249.

That's like our big goal for now. I wouldn't want to merge this pre-v1 to have more work later on to put on par with v1.

Sorry again.
You did a great job here. Probably this component didn't event change much.

On the v1 branch we're already automatically importing sass styles from angular material. No more copy pasting. I really wanted to push that vision into others. It will make ember-paper a much bigger, solid thing.

**Comment by jamesdixon** [comment]
@chrisitananese I'm working on getting this 1.x compatible and had a quick question for you:

The `md-css-variables` line [here](https://github.com/chrisitananese/ember-paper/blob/42d8805b5f293f68acca97dc6672dab23d02cd05/addon/components/paper-fab-speed-dial.js#L81) is pointing to an empty `div` in the component, which is then throwing an error when it tries to parse the value of that `div` into an `integer`. Do you have any idea what's supposed to go here?

**Comment by miguelcobain** [comment]
Closing this as we already have the speed dial implementation.

**Pull request closed without merging**
