### PR TITLE
Feature: Progress Linear/Circular Component

### PR DESCRIPTION
**Pull request by peec**
This PR gives 2 new components:

- Progress Circular
- Progress Linear

These works just like ember-material-design.

Converted from http://mike1234.com/ember-material-design/ ( Thanks @mike1o1  ).

Notes:
- Added [Sniffer service](https://github.com/mike1o1/ember-material-design/blob/master/app/services/sniffer.js). Also added a modified service of "constants", named "browser-compatibility" which is used by the linear progress component. A service fits very well for this purpose because the detection only needs to be done once and not per component basis. So I also added these services which the progress-linear component needs to create dynamic `transforms` attribute on the DOM.

### CODE REVIEW

**Comment by peec** [comment]
@miguelcobain This PR ( progress-linear ) is now the only thing left before autocomplete #132 is done. This PR implemented as ember-material-design. Could you take a look and possibly merge this when you have time?

**Comment by peec** [comment]
@miguelcobain I see that progress-linear is now merged, thanks. I did some changes today, in this PR to also include paper-progress-circular as well. Should i create a new PR for progress circular now that linear is in master?

**Comment by miguelcobain** [comment]
@peec A new PR would be awesome!

**Comment by peec** [comment]
Closed, ref #136

**Pull request closed without merging**
