### PR TITLE
Fix[1134] mouseEnter/Leave/Move deprecations by adding event listeners

### PR DESCRIPTION
**Pull request by Shajansheriff**
Fix [1134](https://github.com/miguelcobain/ember-paper/issues/1134)

### CODE REVIEW

**Comment by betocantu93** [comment]
interesting, I didn't realized you could write native class for mixins!

**Comment by Shajansheriff** [comment]
@betocantu93 We have to replace mixins with native class or with some other patterns. Mixins are going to be removed, however we need to have a roadmap for refactor, because we are using quite a handful of mixins in our addon.

**Comment by Shajansheriff** [comment]
@miguelcobain Do you have any idea why those two specific tests are failing? It is passing in my local.

**Comment by miguelcobain** [comment]
@Shajansheriff interesting workaround for the deprecation. That didn't cross my mind.
The failing tests are unrelated, as you probably guess.
Those tests are flaky, and I suspect are related to using ember vertical collection. Usually they pass after retrying them some times.
Since it's related I'll merge this even if they don't pass.

**Comment by alex9nadon** [comment]
@miguelcobain  Hi, did you plan to merge and create a new release?

**Pull request merged**
