### PR TITLE
Fix code sample indentation on sidebar page

### PR DESCRIPTION
**Pull request by Turbo87**

### CODE REVIEW

**Comment by Turbo87** [comment]
@miguelcobain any comments!?

**Comment by miguelcobain** [comment]
Restarted travis. But I'm sure this doesn't break tests.
Sorry for taking so much time.

**Comment by Turbo87** [comment]
@miguelcobain not sure what's wrong with the default config run, but the others seem to work fine now

**Comment by miguelcobain** [comment]
@Turbo87 This has conflicts. Can you rebase, please?

**Comment by knownasilya** [comment]
This has been fixed in https://github.com/miguelcobain/ember-paper/pull/253

**Comment by miguelcobain** [comment]
This was already fixed, but not published. Thanks for the PR anyway!

**Pull request closed without merging**
