### PR TITLE
Autocomplete inner text

### PR DESCRIPTION
**Pull request by ibarrick**
pass the attrs block into the trigger so that if the user ops into tracking searchText manually, the component will have referential transparency.

### CODE REVIEW

**Comment by ibarrick** [comment]
@xomaczar That's probably why the tests for earlier versions failed. Any idea what else I can use? I need to see if the user passed in searchText and ignore innerText if they did.

**Comment by xomaczar** [comment]
Why do we define searchText as an empty string in autocomplete component? If we set it to undefined you can just compare against that.

**Comment by ibarrick** [comment]
@xomaczar That works to change the text underlying the input but now I'm running into an issue where the options array is still filtered in an unexpected manner. We need an e-p-s way of initializing searchText (which is stored in publicAPI) since that governs what options show up.

**Comment by ibarrick** [comment]
@miguelcobain I changed the component to use the `searchText` variable that was already built into e-p-s which helped resolve a lot of other issues I discovered such as the options array not being updated when the `searchText` attribute changed. I'm not sure why we implemented it outside of e-p-s in the first place but it seems to work this way.

**Comment by xomaczar** [comment]
So is searchText two way bound or not - We are still exposing onSearchTextChanged and user must mutate the searchText himself

**Comment by ibarrick** [comment]
I found all kinds of issues with this once I started using it in production. I'm going to try to work through them and hopefully what comes out will be mergeable.

**Comment by xomaczar** [comment]
Yeah I knew there was a reason we did not use it before :)

**Comment by xomaczar** [comment]
@ibarrick can we close this. Was addressed in #956

**Pull request closed without merging**
