### PR TITLE
Listen for model changes

### PR DESCRIPTION
**Pull request by TNAJanssen**
When changing model, change searchText

### CODE REVIEW

**Comment by TNAJanssen** [comment]
@miguelcobain  when do you have time to check this PR?

**Comment by miguelcobain** [comment]
@TNAJanssen looks good.

Two things:
- please use `'` instead of `"` to conform the code style
- can you please add an entry to the changelog?

**Comment by TNAJanssen** [comment]
@miguelcobain will do!

**Comment by TNAJanssen** [comment]
@miguelcobain what version number?

**Comment by miguelcobain** [comment]
Under `0.2.9`, and update date, please.

**Comment by TNAJanssen** [comment]
@miguelcobain  done

**Comment by TNAJanssen** [comment]
@miguelcobain can you merge this

**Pull request merged**
