### PR TITLE
Upgrade dependencies incl. Ember 2.14

### PR DESCRIPTION
**Pull request by bjornharrtell**
Appears to be working fine except the virtual repeat.

Remaining tasks:

* [x] Fix lint problems
* [x] Fix "Assertion Failed: Cannot call get with 'options' on an undefined object." in the virtual repeat sample
* [x] Fix qunitjs upgrade issues

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Ready for review.

**Comment by bjornharrtell** [comment]
Forgot to check qunit issues. Will do so and return with a new reviewable state.

**Comment by bjornharrtell** [comment]
Hit by the qunit issue as fixed/described by https://github.com/miguelcobain/ember-paper/pull/694 only this time it does not appear to help to pin the qunitjs version. :(

**Comment by bjornharrtell** [comment]
I just now noticed that running a failing test in isolation makes it pass.

**Comment by bjornharrtell** [comment]
Think I've found the test case issue and fixed it. The Ember beta build fails at CI but I suspect it has nothing to do with this PR.

**Comment by bjornharrtell** [comment]
Rebased. CI fails completely but I don't understand why, it seems it's not using the `.travis.yml` that's in this branch (unchanged from master).

**Comment by bjornharrtell** [comment]
Rebased again. Still failing at CI but it runs as expected, failure is with ember-beta which is the same on the master branch.

**Comment by bjornharrtell** [comment]
Rebased and squashed.

**Comment by miguelcobain** [comment]
beta and canary are expected to fail. It's an upstream problem.
Thanks for this. Will merge once tests finish running.

**Pull request merged**
