### PR TITLE
Change ember-power-select version to fix broken paper-menu

### PR DESCRIPTION
**Pull request by caiorasc**
Hello, I am with the same problem described on [#1035](https://github.com/miguelcobain/ember-paper/issues/1035) issue. Following @panthony issue, I could fix the problem forcing ember-power-select version to 2.0.3.
I don't know if this is a valid pull request, it's my first one 😅. But I will try, because the project depends of ember-paper.

### CODE REVIEW

**Comment by panthony** [comment]
Did you try the beta 21? Maybe it was fixed by https://github.com/miguelcobain/ember-paper/commit/01229aec64dce6a9d2859e39a0d0402a974408ba

**Comment by caiorasc** [comment]
Oh, I will try

**Comment by miguelcobain** [comment]
@caiorasc did it work?

**Comment by caiorasc** [comment]
Yes, sorry for the mistake

**Pull request closed without merging**
