### PR TITLE
Upgrade to virtual-each 0.6.0

### PR DESCRIPTION
**Pull request by bjornharrtell**

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Realize now that yarn.lock need an update for this. Will fix ASAP.

**Comment by Subtletree** [comment]
There's #906 open too, removing virtual-repeat so might not need this one.

**Comment by bjornharrtell** [comment]
Ah that seems nice, but I can't fully understand the changes in that PR.

My reason for doing this is to get rid of Babel 5 usage in ember-paper which I think is only because virtual-each 0.5.x at this point.

**Comment by Subtletree** [comment]
Yeah I've been getting that deprecation too.

I think the idea is to let users handle `virtual-repeat`/ infinite-scroll themselves, using addons specifically designed for the task. https://github.com/miguelcobain/ember-paper/issues/631#issuecomment-288748440

**Comment by bjornharrtell** [comment]
Sounds reasonable, but it looks like the PR is not complete. So I will attempt to get this passing.

**Comment by bjornharrtell** [comment]
Unfortunately I now notice that there are several other deps that are out of date. AFAICT these are `ember-deferred-content`, `liquid-fire`, `ember-cp-validations`, `ember-transition-helper` and `ember-cli-fastboot`. Will attempt upgrading them in a separate PR.

**Pull request closed without merging**
