### PR TITLE
Upgrade Ember

### PR DESCRIPTION
**Pull request by bjornharrtell**
Depends on #689.

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Rebased.

**Comment by bjornharrtell** [comment]
Another rebase with additional upgrades.

**Comment by bjornharrtell** [comment]
With the latest round of updates including adaptions with a `ember init` run, the default package manager is now yarn and the qunit problem that was worked around by using an older version (#694) is no longer needed.

**Comment by bjornharrtell** [comment]
Appears I made a premature conclusion, the qunit issue is still there. The yarn.lock was not upgraded.

**Comment by miguelcobain** [comment]
Thanks!

**Pull request merged**
