### PR TITLE
Dialogs

### PR DESCRIPTION
**Pull request by peec**
Supports:
- Angular SCSS
- Animations - translate3d mixin was needed as it's not the same concepts as regular css animations and rather computed styles with JS.
- All dialog specific feature works.

Can be enhanced with: keyevents + some button focusing on e.g. confirm dialog, but I currently have no time to do that.

### CODE REVIEW

**Comment by jamesdixon** [comment]
any plans on merging this one in anytime in the near future? thanks!

**Comment by miguelcobain** [comment]
This PR needs a rebase. :cry:

**Comment by afomi** [comment]
bump (and nice feature!)

**Comment by miguelcobain** [comment]
@peec I suspect you have less time now, but I wonder if you could work to make this on par with #249. It will be the big thing in ember-paper.

**Comment by peec** [comment]
@miguelcobain Yup you are correct, awesome work you did there, I have had no time for this lately. I will see if I can find time for it - I guess I soon will have,

**Comment by DanChadwick** [comment]
Thanks for the effort here. I would love to see this merged.

**Pull request closed without merging**
