### PR TITLE
Update blocking dependencies and codebase

### LINKED ISSUE #635: Backdrop problems back again.
Since version 1.0.14 
Backdrop getting stucked randomly when paper-sidenav is opened repeatedly.

### LINKED ISSUE #688: Select options don't change focus when using arrow keys
When moving between select options with up and down keys, ember-power-select uses `aria-current=true` to show what option is focused by adding styles to `.ember-power-select-option[aria-current=true]`.

 Angular material uses the `:focus` selector to show what option is focused.

Since `paper-select` doesn't focus the options the focused option is never shown:
screen shot 2017-04-11 at 5 11 31 pm

Angular's version:
screen shot 2017-04-11 at 5 04 03 pm

If I was to put a pull request together for this, would it be preferable to:

1. Keep to spec and make ember-power-select focus the options.
2. Add the styles to `[aria-current=true]`

### LINKED ISSUE #777: paper-select: should be able to focus an entry by pressing keys
Like it does in angular implementation (or a regular select):

https://material.angularjs.org/latest/demo/select

Related to #688 since it is necessary to have the focus state fixed for this to work.

### LINKED ISSUE #808: Select options inside a dialog remain open when closing dialog using the ESC key.
I have several paper-selects on a paper-dialog. If the ESC key is pressed while having a paper-select options box open, the modal closes but the options box remains open and unclosable cause its select component isn't on the template anymore. Any idea on how to solve this without disabling the ESC key?

### LINKED ISSUE #925: paper-select causes the app to become unresponsive
Occasionally (5 or 10% of the time) `paper-select` causes my app to become unresponsive.

When this occurs the `#ember-basic-dropdown-wormhole` contains both an `md-backdrop` element and a div for the dropdown content `#ember-basic-dropdown-content-...`.

The content div returns the following from `getBoundingClientRect()`, making it invisible and unclickable:
```
{
  "x": 0,
  "y": 0,
  "width": 0,
  "height": 0,
  "top": 0,
  "right": 0,
  "bottom": 0,
  "left": 0
}
```

The `md-backdrop` element masks the rest of the app and _does not respond to clicks_ making the app unresponsive. There are no errors in the console.

The only other unusual thing about this use case is that the drop down exists in a modal (which animates open) which has tabs (with animations between tabs). Could the animation of the parent context be causing this bug?

### Related (?) Bugs

This was observed with both Ember 3.0.0 and 3.1 applications. ~~I'm also using `paper-select` with a 3.0 application and this behavior does not occur~~

I do sometimes experience two other issues which I'll write up separately:
- sometimes the options list appears a few hundred px above the expected location
- sometimes the user has to click multiple times to make a selection

### LINKED ISSUE #967: paper-select-dropdown persists when dialog is closed
##   STEPS
  - Open the dialog
  - click on the category field to open drop down
  - hit ESCAPE
  - the dropdown HTML should persist
  - the components are destroyed (judging based on what ember-inspector shows)

## The heroku app
https://morning-headland-34714.herokuapp.com/

## Repo
https://github.com/BobrImperator/dropdown-not-closing-on-escape

### LINKED ISSUE #1067: paper-select click outside not closing dropdown menu
Clicking outside the select box doesn't close the dropdown menu. 

**Environment** 
- Device: Mac
- Browser: Chrome
- Ember-CLI: Latest

**Steps to reproduce:** 
1. Run ember init
2. Run ember install ember-paper
3. Add select from example to the application hbs
4. Optional: define options for select. This isn't required because it will show results not found in the menu. 
5. Click on the option box. 
6. Click somewhere else on the page.

Am i missing something here?

### LINKED ISSUE #1165: Deprecations when upgrading to Ember >= v3.20.x, {{-in-element}}
A few components in `ember-paper` rely on the private Ember API of `{{-in-element}}`, everything after Ember v3.20.x has deprecated that private API in favor of the now public `{{in-element}}`. https://github.com/emberjs/ember.js/releases/tag/v3.20.0

[RFC for this change in Ember](https://github.com/emberjs/rfcs/blob/master/text/0287-promote-in-element-to-public-api.md)

Example: https://github.com/miguelcobain/ember-paper/blob/master/addon/templates/components/paper-tooltip.hbs

### LINKED ISSUE #1166: Paper select errors when menu is closed on ember > 3.17
When you open a <PaperSelect ... /> and then close the menu, you'll see this error show up in the console.

`
component.js:65 Uncaught (in promise) TypeError: Cannot read property 'appendChild' of null
    at PaperMenuContent.animateOut (component.js:65)
    at Object.destroyModifier (will-destroy.js:68)
    at CustomModifierState.destroy (index.js:6906)
    at StringDestroyableDestructor.[DID_DROP] (util.js:290)
    at util.js:201
    at Set.forEach (<anonymous>)
    at didDestroyAssociated (util.js:200)
    at SimpleDestructor.[DID_DROP] (util.js:314)
    at util.js:201
    at Set.forEach (<anonymous>)
`

The issue is from ember-power-select and you can see the relevant issues at:
https://github.com/cibernox/ember-power-select/issues/1338 (fixed here)
https://github.com/cibernox/ember-basic-dropdown/issues/540

The fix was released in ember-power-select 4.0.

I was able to verify the issues goes away by forcing ember-power-select to resolve to 4.0.4.

I see that ember-power-select requires ember 3.13 which is a year old, but this seems worth it as we would be totally blocked from upgrading without forcing the resolution.

### LINKED ISSUE #1180: error when building app with ember-paper
Hi, 
I run into this issue as soon as I add ember-paper to any project:

    Template Compiler Error (broccoli-persistent-filter:TemplateCompiler) in ember-basic-dropdown/templates/components/basic-dropdown-content.hbs
    
    Cannot read property 'type' of undefined

I am using Ember 3.25.0 and ember-paper 1.0.0-beta.35.

### LINKED ISSUE #1191: Ghost basic-dropdown-content once paper-menu closed
Hello there!

We just discovered a bug in an app we develop for years now. A thorough test of the app after upgrading to Octane syntax revealed an annoying behaviour: once closed, the paper-menu-content `<div>` is cloned and left in place, invisible, on top of all the other GUI elements, catching all the clicks and preventing all interactions with the buttons behind.

On click, the menu opens:

ember-paper paper-menu open

On click outside, the menu closes but a cloned `<div>` is left behind:

ember-paper paper-menu ghost

```
DEBUG: Ember             : 3.18.1
DEBUG: Ember Data        : 3.18.0
DEBUG: jQuery            : 3.3.1
DEBUG: Ember Paper       : 1.0.0-beta.35
```
No related errors in the console.

This behaviour is present from the `beta.23` at least. We just upgraded to the latest beta to see if it fixes it, but unfortunately not.

Have you ever stumbled upon this kind of trouble? Do you know how to fix it?

Thanks!

### PR DESCRIPTION
**Pull request by Subtletree**
Had some spare work time at the end of the year to remove deprecations and blocking dependencies. I know ember-paper is basically unmaintained at this stage but this move for now is easier than moving to something else or moving to styles other than angular-material v1...

- Updated ember-basic-dropdown and ember-power-select and refactored relevant code.
- Updated dummy app to ember/ember-cli 3.28.
- Removed/updated outdated dependencies.

Everything's ready to go as far as I know except for the toast css-transitions. Hopefully wrap that up on monday.

closes #1180, closes #1179, closes #1176, closes #1166, closes #1175, closes #1191, closes #1192, closes #1165, closes #1067, closes #808, closes #967, closes #925, closes #777, closes #688, closes #635

### CODE REVIEW

**Comment by miguelcobain** [comment]
Thank you so much for this. 👍

**Comment by Subtletree** [comment]
@miguelcobain This is good to go. We've been using in production for a week and ironed out a couple of issues. More might crop up but I'm happy to fix bugs related to this as they come up.

Should let people upgrade to 3.28 LTS atleast and we can evaluate what more needs to be done and if it's worth supporting ^4 without changing from angular styles v1.

**Comment by miguelcobain** [comment]
@Subtletree I gave you permission to update the repository and the npm package. Hopefully you can bring this project to a decent place.
You have my utmost respect, sir.

**Comment by creising** [comment]
@Subtletree you are a legend! Thank you for this!

**Comment by Subtletree** [comment]
> @Subtletree I gave you permission to update the repository and the npm package. Hopefully you can bring this project to a decent place. You have my utmost respect, sir.

What an honour! I can't promise to continue upkeep in the long term but if others are still interested we might be able to keep EP alive.

Thanks so much for the work you've put in with ember-paper over the years. What a major effort keeping it rolling since 2014!

Version 1.0.0-beta.36 is published 🎉

**Pull request merged**
